spring:

  ## 1. DB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx.xxx.xxx.xxx:13306/CDD_BIZ_COMMODITY?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ddphin
    password: ddphin

    ## 2. Hikari datasource
    hikari:
    minimum-idle: 5
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    pool-name: DatebookHikariCP
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1


  redis:
    database: 0
    host: xxx.xxx.xxx.xxx
    port: 16379
    password: ddphin
    timeout: 60s

  rabbitmq:
    host: xxx.xxx.xxx.xxx
    port: 15674
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 15000
    template:
      mandatory: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
    publisher-confirms: true
    publisher-returns: true
server:
  servlet:
    context-path: /api #设置项目ContextPath
  port: 8080 #设置Tomcat端口，默认8080
  tomcat:
    uri-encoding: UTF-8 #设置Tomcat编码
